/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PartnershipsRouteImport } from './routes/partnerships'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as DevelopmentRouteImport } from './routes/development'
import { Route as DasherHouseRouteImport } from './routes/dasher-house'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConsultancyRouteImport } from './routes/consultancy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipsRoute = PartnershipsRouteImport.update({
  id: '/partnerships',
  path: '/partnerships',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentRoute = DevelopmentRouteImport.update({
  id: '/development',
  path: '/development',
  getParentRoute: () => rootRouteImport,
} as any)
const DasherHouseRoute = DasherHouseRouteImport.update({
  id: '/dasher-house',
  path: '/dasher-house',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultancyRoute = ConsultancyRouteImport.update({
  id: '/consultancy',
  path: '/consultancy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consultancy': typeof ConsultancyRoute
  '/contact': typeof ContactRoute
  '/dasher-house': typeof DasherHouseRoute
  '/development': typeof DevelopmentRoute
  '/insights': typeof InsightsRoute
  '/partnerships': typeof PartnershipsRoute
  '/portfolio': typeof PortfolioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consultancy': typeof ConsultancyRoute
  '/contact': typeof ContactRoute
  '/dasher-house': typeof DasherHouseRoute
  '/development': typeof DevelopmentRoute
  '/insights': typeof InsightsRoute
  '/partnerships': typeof PartnershipsRoute
  '/portfolio': typeof PortfolioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consultancy': typeof ConsultancyRoute
  '/contact': typeof ContactRoute
  '/dasher-house': typeof DasherHouseRoute
  '/development': typeof DevelopmentRoute
  '/insights': typeof InsightsRoute
  '/partnerships': typeof PartnershipsRoute
  '/portfolio': typeof PortfolioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/consultancy'
    | '/contact'
    | '/dasher-house'
    | '/development'
    | '/insights'
    | '/partnerships'
    | '/portfolio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/consultancy'
    | '/contact'
    | '/dasher-house'
    | '/development'
    | '/insights'
    | '/partnerships'
    | '/portfolio'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/consultancy'
    | '/contact'
    | '/dasher-house'
    | '/development'
    | '/insights'
    | '/partnerships'
    | '/portfolio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConsultancyRoute: typeof ConsultancyRoute
  ContactRoute: typeof ContactRoute
  DasherHouseRoute: typeof DasherHouseRoute
  DevelopmentRoute: typeof DevelopmentRoute
  InsightsRoute: typeof InsightsRoute
  PartnershipsRoute: typeof PartnershipsRoute
  PortfolioRoute: typeof PortfolioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnerships': {
      id: '/partnerships'
      path: '/partnerships'
      fullPath: '/partnerships'
      preLoaderRoute: typeof PartnershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development': {
      id: '/development'
      path: '/development'
      fullPath: '/development'
      preLoaderRoute: typeof DevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dasher-house': {
      id: '/dasher-house'
      path: '/dasher-house'
      fullPath: '/dasher-house'
      preLoaderRoute: typeof DasherHouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultancy': {
      id: '/consultancy'
      path: '/consultancy'
      fullPath: '/consultancy'
      preLoaderRoute: typeof ConsultancyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConsultancyRoute: ConsultancyRoute,
  ContactRoute: ContactRoute,
  DasherHouseRoute: DasherHouseRoute,
  DevelopmentRoute: DevelopmentRoute,
  InsightsRoute: InsightsRoute,
  PartnershipsRoute: PartnershipsRoute,
  PortfolioRoute: PortfolioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
